# Generated by Django 3.2.9 on 2021-11-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211121_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='عکس'),
        ),
    ]
