# Generated by Django 3.2.9 on 2021-12-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PUB', 'publish'), ('DRF', 'draft')], default='PUB', max_length=3, verbose_name='status of post'),
        ),
    ]
