# Generated by Django 3.2.9 on 2022-01-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220109_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_organizer',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profile', verbose_name='image of profile user'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sexuality',
            field=models.CharField(choices=[('male', 'male'), ('fmle', 'female')], default=1, max_length=4, verbose_name='select your gender'),
            preserve_default=False,
        ),
    ]
