# Generated by Django 3.2.9 on 2022-01-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220110_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sexuality',
            field=models.CharField(choices=[('male', 'male'), ('fmle', 'female')], default='male', max_length=4, verbose_name='select your gender'),
        ),
    ]
