# Generated by Django 3.2.10 on 2022-01-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220114_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this user has verified phone', verbose_name='verified'),
        ),
    ]
