# Generated by Django 3.2.10 on 2022-01-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='key',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
