# Generated by Django 3.2.9 on 2021-12-29 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_image_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='thumbnail',
            new_name='thumbnaill',
        ),
    ]
