# Generated by Django 3.2.9 on 2021-12-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_thumbnail_picture_thumbnaill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='thumbnaill',
            new_name='thumbnail',
        ),
    ]
