# Generated by Django 3.2.9 on 2022-01-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_cart_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_number',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
    ]
